### ISSUE TITLE
uBridge is not available or path does not exist

### ISSUE THREAD

**Issue by EarlRamirez** [GNS3/gns3-server#1247]
After upgrading to Fedora 27 and gns3-server 2.1 I am no longer able to connect any devices, each time I try I get the following error 
"Error while creating link: uBridge is not available, path doesn't exist, or you just installed GNS3 and need to restart your user session to refresh user permissions"

I have checked to see if there is any ubridge package and there are no package available; however, I do see that there is folder provided by the server package gns3-server-2.0.3-7.fc27.noarch which is "/usr/lib/python3.6/site-packages/gns3server/ubridge"

I have also restarted the computer a few times; however, it made no difference, are there any suggestions on how to resolve this?

**Comment by grossmj** [comment]
What is the output of `whereis ubridge` command?

**Comment by EarlRamirez** [comment]
@grossmj, unfortunately, it only returns 
ubridge: 
I installed it using @athmane  corp repo on Fedora worked perfectly on F25 and F26 and never checked to see if and where ubridge was installed because it worked.
dnf search ubridge returns no matches found and 
dnf whatprovides */ubridge, return the following:
dnf whatprovides */ubridge
Last metadata expiration check: 16:41:08 ago on Sun 07 Jan 2018 13:38:57 EST.
gns3-server-2.1.0-1.fc27.noarch : Graphical Network Simulator 3
Repo        : @System
Matched from:
Filename    : /usr/lib/python3.6/site-packages/gns3server/ubridge

gns3-server-2.1.0-1.fc27.noarch : Graphical Network Simulator 3
Repo        : updates
Matched from:
Filename    : /usr/lib/python3.6/site-packages/gns3server/ubridge

gns3-server-2.0.3-7.fc27.noarch : Graphical Network Simulator 3
Repo        : fedora
Matched from:
Filename    : /usr/lib/python3.6/site-packages/gns3server/ubridge

This is a directory with a few python files.

**Comment by grossmj** [comment]
Unfortunately we cannot provide good support for non Debian based Linux distro, I would suggest to post on gns3.com to find out how others did it. I would try to manually compile and install uBridge: https://github.com/GNS3/ubridge#installation

**Comment by EarlRamirez** [comment]
Thanks, @grossmj I will build a package for RPM based distro if I can't find one that works. You can proceed to close this issue.

**Comment by jkk88** [comment]
Got the same error on remote debian 9 server.
This commands help me to fix this issue:
    usermod -a -G libvirt-qemu gns3
    usermod -a -G gns3 gns3

**Comment by shiblovich** [comment]
i get solution you just need to install ubridge download it 
git clone git://github.com/GNS3/ubridge.git
cd ubridge
make
sudo make install 
and try again

**Comment by andresn19** [comment]
thanks @shiblovich it works

**Comment by PranavBhattarai** [comment]
![Screenshot from 2020-11-28 14-24-26](https://user-images.githubusercontent.com/32763112/100497730-75b2de00-3185-11eb-9c8b-9132dea1f235.png)
**Ubridge** is not installed but weirdly it gives me this output in Ubuntu 20.10.
Is cloning the repo is only solve this problem?! @grossmj

**Comment by TobjasR** [comment]
simply `chmod +x ubridge` worked for me :)

**Comment by kraluc** [comment]
BEFORE trying make and sudo make install...

ensure that you have the following installed FIRST:  ***lacking gcc*** caused make to fail. 
(I realize that this is a newbie mistake but since most documentation does not call this out explicitly...)

sudo apt install git -y
sudo apt install make -y
sudo apt install gcc -y
sudo apt install libpcap-dev -y
cd /tmp
git clone https://github.com/GNS3/ubridge.git
cd ubridge
make
sudo make install


This is how it looked for me after the make step:

gns3@gns3:/tmp$ cd ubridge/

gns3@gns3:/tmp/ubridge$ make
cc -Wall -DLINUX_RAW   -c -o src/ubridge.o src/ubridge.c
cc -Wall -DLINUX_RAW   -c -o src/nio.o src/nio.c
cc -Wall -DLINUX_RAW   -c -o src/nio_udp.o src/nio_udp.c
cc -Wall -DLINUX_RAW   -c -o src/nio_unix.o src/nio_unix.c
cc -Wall -DLINUX_RAW   -c -o src/nio_ethernet.o src/nio_ethernet.c
cc -Wall -DLINUX_RAW   -c -o src/nio_tap.o src/nio_tap.c
cc -Wall -DLINUX_RAW   -c -o src/parse.o src/parse.c
cc -Wall -DLINUX_RAW   -c -o src/packet_filter.o src/packet_filter.c
cc -Wall -DLINUX_RAW   -c -o src/pcap_capture.o src/pcap_capture.c
cc -Wall -DLINUX_RAW   -c -o src/pcap_filter.o src/pcap_filter.c
cc -Wall -DLINUX_RAW   -c -o src/hypervisor.o src/hypervisor.c
cc -Wall -DLINUX_RAW   -c -o src/hypervisor_parser.o src/hypervisor_parser.c
cc -Wall -DLINUX_RAW   -c -o src/hypervisor_bridge.o src/hypervisor_bridge.c
cc -Wall -DLINUX_RAW   -c -o src/nio_linux_raw.o src/nio_linux_raw.c
cc -Wall -DLINUX_RAW   -c -o src/hypervisor_docker.o src/hypervisor_docker.c
cc -Wall -DLINUX_RAW   -c -o src/hypervisor_iol_bridge.o src/hypervisor_iol_bridge.c
cc -Wall -DLINUX_RAW   -c -o src/hypervisor_brctl.o src/hypervisor_brctl.c
cc -Wall -DLINUX_RAW   -c -o src/netlink/nl.o src/netlink/nl.c
cc -Wall -DLINUX_RAW   -c -o src/iniparser/iniparser.o src/iniparser/iniparser.c
cc -Wall -DLINUX_RAW   -c -o src/iniparser/dictionary.o src/iniparser/dictionary.c
cc -Wall -DLINUX_RAW  -o ubridge src/ubridge.o src/nio.o src/nio_udp.o src/nio_unix.o src/nio_ethernet.o src/nio_tap.o src/parse.o src/packet_filter.o src/pcap_capture.o src/pcap_filter.o src/hypervisor.o src/hypervisor_parser.o src/hypervisor_bridge.o src/nio_linux_raw.o src/hypervisor_docker.o src/hypervisor_iol_bridge.o src/hypervisor_brctl.o src/netlink/nl.o src/iniparser/iniparser.o src/iniparser/dictionary.o -lpthread -lpcap


gns3@gns3:/tmp/ubridge$ sudo make install
chmod +x ubridge
cp -p ubridge /usr/local/bin
setcap cap_net_admin,cap_net_raw=ep /usr/local/bin/ubridge
