### ISSUE TITLE
GNS3 Server 2.1.5 - async-timeout - Ubuntu Trusty

### ISSUE THREAD

**Issue by alexandrecorso** [GNS3/gns3-server#1331]
I updated my GNS3-server from 2.1.4 to 2.1.5 (GNS3 VM - Ubuntu Trusty) and I found one problem with le library async-timeout. The new release of async-timeout (3.0 https://pypi.org/project/async_timeout/) do not support python 3.4. 
My solution, I've re-install the library with the version 2.0.1.

Maybe you should install the maximum version of async-timeout on your upgrade script.

Alexandre Corso

**Comment by int3l** [comment]
We just need to downgrade the damn async_timeout lib..., because basically the main dev did a yolo move by removing the support for python 3.4 - [Typing (#37) - Add type annotations, drop python 3.4](https://github.com/aio-libs/async-timeout/commit/28f96b7197f58a7642d140005a92887834cbaf8c#diff-493ea624ff112f6c11829580872c5833L40)

The problem is not that the support for python 3.4 is dropped, but the way of doing it...

**Comment by int3l** [comment]
Temporary workaround for all users that face the problem:

- Go to the Menu
- Choose 'Shell' option
- Execute the following command `sudo pip3 install -U async_timeout=2.0.1`
- Exit the shell (with typing `exit` once o twice)
- Done

**Comment by ziajka** [comment]
Thank you @alexandrecorso and @int3l, fix goes in the next release (probably next week).
