### ISSUE TITLE
Question: GNS3 remote server resource overallocation

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1543]
Hi,

I've using GNS3 remote server (V2.1.11) for running QEMU appliances. My appliance consumes:
2vCPU
2 GB RAM

So if I have GNS3 remote server with ~20vCPU and ~20GB RAM, I can run up to 10 such appliances.
However, not all the appliances are concurrently utilized, so I would like to run more appliances than available resources.

So my question is whether GNS3 run QEMU appliances with hard allocation of resources, and thus overallocation will not work, or else I should benefit from overallocation?

Doron

**Comment by grossmj** [comment]
I think you should be able to over-allocate because of various Qemu/Linux optimizations, especially if you use the same Qemu image across your projects. For instance, one optimization is KSM (https://www.linux-kvm.org/page/KSM) which should be enabled by default (check with cat /sys/kernel/mm/ksm/run)

However, I haven't tested anything myself and would love to hear about your results.
