### ISSUE TITLE
Question: How GNS3 manages console ports

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1581]
Hi Team,

I'm interested in understanding how GNS3 manages console ports. Example questions I have:
1) Is there a pool from which GNS3 allocate ports?
2) When port is popped of the pool and when it is pushed back?
3) How GNS3 manages the port forwarding that allows me to telnet GNS3 host but actually access the running node?

Doron

**Comment by grossmj** [comment]
> Is there a pool from which GNS3 allocate ports?

Yes, GNS3 will allocate a port from a specified range. This range can be configured for the local server from the GUI in server preferences or by editing the gns3_server.conf file (for local or remote server): https://github.com/GNS3/gns3-server/blob/2.1/conf/gns3_server.conf#L25

> When port is popped of the pool and when it is pushed back?

A port is allocated when a node is created and released when a node is deleted or the project that the node belongs to is closed.

> How GNS3 manages the port forwarding that allows me to telnet GNS3 host but actually access the running node?

We have a simple embedded telnet server that we launch for each console port managed by GNS3. Anything sent/received on this port is forwarded to/from running node, usually on its serial port depending on the emulator.

Let me know if you have more questions.

**Comment by doronbl** [comment]
@grossmj One small question: by saying 'embedded telnet server' do you mean GNS3 server spawn new thread to handle telnet and then forward the packets to the running qemu node?
I guess that GNS3 server forward the packets to the qemu node end point configured by: -serial telnet:127.0.0.1:<port>; Is that correct?

Doron

**Comment by grossmj** [comment]
@doronbl 

> One small question: by saying 'embedded telnet server' do you mean GNS3 server spawn new thread to handle telnet and then forward the packets to the running qemu node?

Correct excepting we use asyncio instead of threads.

We start Qemu with `-serial telnet:127.0.0.1:xxx,server,nowait`, xxx is a port number taken from the console port range, then we start our small embedded telnet server to handle Telnet connections on the node's console port.

The Telnet server is like a proxy allowing communications between Telnet and serial, also it can handle multiple clients connected at the same time.

For reference, here is the source code: https://github.com/GNS3/gns3-server/blob/2.1/gns3server/utils/asyncio/telnet_server.py
