### ISSUE TITLE
PPA for Ubuntu 19.04

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#1583]
User request: https://gns3.com/community/discussion/ubuntu-19-04-support

**Comment by grossmj** [comment]
I have pushed packages for Ubuntu 19.04 but gns3-server could not be built on Launchpad. Looks like there is a problem with one of our dependency.

**Comment by grossmj** [comment]
Also, note to myself: gns3-gui should not depend on gns3-server.

**Comment by grossmj** [comment]
This is the build error on Launchpad, https://launchpadlibrarian.net/424027135/buildlog_ubuntu-disco-amd64.gns3-server_2.1.16~disco2_BUILDING.txt.gz
```
Collecting aiohttp<2.4.0,>=2.3.3 (from -r ./requirements.txt (line 2))
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
Command "/<<PKGBUILDDIR>>/debian/gns3-server/usr/share/gns3/gns3-server/bin/python -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qp0nkqfq --no-warn-script-location -v --no-binary :none: --only-binary :none: --no-index --find-links file:///<<PKGBUILDDIR>>/debian/pypi -- setuptools>=38.2.5 wheel" failed with error code 1 in None
```

I don't understand why we have this issue, it used to work before. I assume the way the dependency is written causes a problem (`aiohttp<2.4.0,>=2.3.3`). I forced the aiohttp dependency to version 2.3.10 because this is the last one supported by GNS3 2.1. I also forced aiohttp-cors version to 0.5.3.

Hopefully this will be enough to solve the build issue.

**Comment by grossmj** [comment]
Let see if it builds after we release version 2.1.17

**Comment by adosztal** [comment]
Thanks, I share the info on the forum.

**Comment by grossmj** [comment]
Unfortunately the build was not successful after we released version 2.1.17

**Comment by grossmj** [comment]
We finally found a workaround that allowed us to build the gns3-server package for Ubuntu disco. Please test and let us know if there is any issue. Thanks :)

**Comment by spickles** [comment]
What's the workaround?

**Comment by grossmj** [comment]
> What's the workaround?

We had to manually build a wheel for aiohttp.
https://github.com/GNS3/gns3-build/commit/929bae5ae7f38151ec7dfcff4134abdcdb0c952d

**Comment by spickles** [comment]
Ugh that sucks

**Comment by grossmj** [comment]
Looks like we are good with this.
