### ISSUE TITLE
The NPF or NPCAP service is not installed

### ISSUE THREAD

**Issue by ghost** [GNS3/gns3-server#1670]
The error message is not valid.
From my understanding, the gns3-server originates the message and
just passes the message to the gns3-gui.
The gns3-server does not generate any output to the gns3-server.log, but instead,
the gns3-server crashes.

The fix was seen in my post:
https://www.gns3.com/community/discussion/the-npf-or-npcap-service-is-no-2

The error message generated and passed to the gns3-gui SHOULD be changed.

All gns3 posts regarding winpcap, and there quite a few, are no longer valid
because winpcap is deprecated in favor of win10pcap. But the gns3 documentation
problem is for another day.

My version of gns3 is 2.1.10 and it is possible that this type of enhancement
was included in a later version of gns3. However, I checked the change log of
either gns3-server, gns3-gui, or both (I did not annotate that), and I found
nothing associated with winpcap.

**Comment by joevizio** [comment]
The gns3-all-in-one installation packages may also not be valid for my 
windows 10 build version, and above, because winpcap has been deprecated in favor of win10pcap.

The win10pcap source code is 5 times the size of the gns3-server source code.
The gns3-server source code is far, far too large for me to comprehend.
I can not go remotely near the win10pcap source code.

**Comment by grossmj** [comment]
@joevizio do you mean that winpcap does not work in the latest Windows update (build 1903)?

**Comment by joevizio** [comment]
I mean something in the upgrade process for Windows 10 build 1903 or VMware Workstation Pro 15.5 uninstalled winpcap from my computer - which makes no sense to me. I looked the situation over to respond to you, but I am not going to uninstall win10pcap/reboot/then install wincpap/then reboot and try gns3 again. It's working fine and it is up to you to do what you want with winpcap/win10pcap transition - if anything

**Comment by grossmj** [comment]
Wireshark uses npcap since version 3.0. I think we should do the same and install npcap by default now.

![Screenshot from 2019-10-30 12-23-51](https://user-images.githubusercontent.com/4752614/67828966-54aa3480-fb10-11e9-9627-b457354d9b11.png)

**Comment by grossmj** [comment]
The GNS3 all-on-one installer will install npcap if running on Windows 10 or above otherwise winpcap will be installed.

**Comment by joemhiggins** [comment]
Hi,

I changed my github username. I upgraded to Wireshark 3.0.6 yesterday on my Windows 10 build 1903.  I have in the past month slowly been working through all the gns3 appliances with my gns3 2.1.10, which I have been using since that version came out, and installing the appliances and just pinging my physical computer as a sanity check so I can safely move to 2.2.2. The standard operating procedure I use is to follow David Bombal's video (https://www.youtube.com/watch?v=Gpje9PV1j8U) and connecting the cloud's eth2. The wireshark upgrade obliterated gns3 2.1.10 and my cloud eth2 is now connected to my npcap as my wireshark captures show and I am no longer able to ping my local computer.

This is not a big deal for me. Whatever is causing the problem, I can find out and I can/will rollback. This will take me some time because I will have to read the wireshark documentation and fire up powershell and proceed very cautiously. I am very concerned that this will affect gns3 users because David Bombal is a powerhouse and Wireshark 3.0.6 just broke his video and gns3 users love to connect to the internet. Furthermore, I do not understand how Wireshark 3.0.6/npcap just broke my gns3 cloud appliance so I do not know how it will affect versions above gns3 2.2.0

Can you please escalate my situation to David Bombal.

**Comment by joemhiggins** [comment]
It is not a big deal for me. I just have to rollback wireshark to the version where gns3 2.1.10 and the cloud appliance will work properly according to Bombal's video. But generally speaking, Wireshark breaking Bombal's is an extremely big deal.

**Comment by joemhiggins** [comment]
Never mind. I uninstalled win10pcap, winpcap, and wireshark. Then from my registry archive, I reinstalled winpcap 4.1.3 and then wireshark 2.6.3. I am not installing win10pcap - gns3 works and that is all I care about (and i turned off checking for updates in wireshark)
