### ISSUE TITLE
Replace zipstream with zstandard compression

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1700]
See https://github.com/GNS3/gns3-server/pull/1693

**Comment by Chewie** [comment]
One unsung hero of this enhancement would be the usage of tar instead of zip, which would allow symlinks in docker appliances to be preserved when doing an export.

I actually stumbled on this issue by searching a way to contribute such an export format for this specific reason, but there's no need if this format is proposed not just for snapshots, but for the whole project!

**Comment by grossmj** [comment]
Zstandard has been added in v3.0 (currently in alpha)
