### ISSUE TITLE
Backup projects from GNS3 VM for Windows users

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1703]
Windows users wanting to backup projects from the GNS3 VM using winscp for instance will be unsuccessful because Docker containers using symbolic links. Should we do something about this?

https://gns3.com/community/discussion/gns3-docker-s-not-really-valid-f

**Comment by joemhiggins** [comment]
Oh, do not worry about it.

To respond to a gns3 poster, I wanted to move all my visios on my C: drive to one specific directory.
Via the powershell command Get-Childitem, my visios showed up in a sub-directory of my c:\Users directory and the same visios showed up in a sub-directory of the shortcut 'c:\Documents and Settings' directory - this really confused me. But I already know I can deal with that scenario.

Long story short, powershell *appears* to have the ability to follow the symbolic links (locally and remotely)  according to:
https://blogs.msdn.microsoft.com/junfeng/2012/05/07/the-symbolic-link-cannot-be-followed-because-its-type-is-disabled/

Using powershell to back up the GNS3 VM will be better for me
because I should be able to customize the backups – which is better.

I do not know for sure yet, because  I have not finished my powershell book and the stuff with
files and directories in powershell about Windows is completely new and complicated :(

I will take care of this.
I already have it in my H for powershell tab in gVim.
Just slap a NOT FIXED on it or whatever :)
