### ISSUE TITLE
Keep old versions in PPA

### ISSUE THREAD

**Issue by PiAil** [GNS3/gns3-server#1775]
Not an issue, but a proposition.

I think it may be a good practice to keep old versions in PPA. 
In the current state, it is impossible to downgrade GNS3, and it may be useful for one hundred reasons.

(In my case, I wanted to test #1773 against 2.2.8, because I'm pretty sure it wasn't there before, and I would have liked to know what changes have triggered that, and their implication).

**Comment by grossmj** [comment]
We don't explicitly remove old versions in our PPA however they are superseded when we push a newer versions.

https://help.launchpad.net/Packaging/PPA

> Packages you publish in your PPA will remain there until you remove them, they're superseded by another package that you upload or the version of Ubuntu against which they're built becomes obsolete.

Not sure if there is a way around that.

**Comment by PiAil** [comment]
After some search, it does not look possible indeed.
I find this really surprising...
Sorry for thinking it was on your side, I thought it was such an obvious feature of packet management, that it was easily feasible.

**Comment by b-ehlers** [comment]
All APT repositories I know keep an older version only for a very short time. But the PPA archive seems to keep old versions a bit longer, so that you have a good chance to get the second last version.

View all versions of all packages GNS3:
<https://launchpad.net/~gns3/+archive/ubuntu/ppa/+packages?field.status_filter=>

As that list is far too long you can use to filter function to make it smaller, for example all versions of the gns3-gui and gns3-server for 18.04:
<https://launchpad.net/~gns3/+archive/ubuntu/ppa/+packages?field.name_filter=gns3-&field.status_filter=&field.series_filter=bionic>

When you expand the interesting package you might see download links in the "Package files" section (if you're lucky). Download the .deb file and install it with `dpkg -i <package file name>`.

In your case for 18.04 the gns3 packages for v2.2.8 are still available, while v2.2.7 are not. So at least when you notice a severe issue of a new version there is a way back to the previous one.
