### ISSUE TITLE
ping physical machine from within machine running in GNS3

### ISSUE THREAD

**Issue by lunhas2k4** [GNS3/gns3-server#1844]
Hi guys, 

Hope you are all well!

I am running gns3 on my fedora 32 machine. I have machines able to ping the internet, my router but for some odd reason not able to ping the the actual host where GNS3 is installed. 
I see that I am not able to get the mac address of the VM in my ARP table for some odd reason. But my VM has  my mac address.
Is there something I am missing?

My mac address on interface enp0s31fe

![Screenshot from 2020-11-23 19-34-17](https://user-images.githubusercontent.com/74929149/100006819-64578380-2dcb-11eb-8250-00850ca0f77d.png)

My mac address table, unable to see mac address of the machine of interest.

![Screenshot from 2020-11-23 19-34-05](https://user-images.githubusercontent.com/74929149/100006825-66214700-2dcb-11eb-9627-8ed838881891.png)

Fortigate VM running in GNS3 sees the right mac address of my interface which it tries to ping.
![Screenshot from 2020-11-23 19-33-49](https://user-images.githubusercontent.com/74929149/100006828-66b9dd80-2dcb-11eb-9c51-21c62a3d9b3c.png)

Has anyone come across this and solved it?

Thanks in advance guys!

**Comment by b-ehlers** [comment]
I assume, you use the cloud with your host ethernet interface (enp0s31f6) to connect your GNS3 node to the physical machine.

That's not working on Linux (and macOS). The reason is, that the data sent by GNS3 to the ethernet cloud interface is directly transmitted on the wire. The TCP/IP system of the host doesn't see these packets, so it can't respond to them. Therfore you are able to send data to all devices on your LAN, including the router to the outside world, but not to your local system.

You need to use TAP or Bridge interfaces to connect the GNS3 nodes with your host. Quite some time ago I wrote a blog post about that: <https://www.b-ehlers.de/blog/posts/2017-07-11-gns3-cloud-linux/>

**Comment by lunhas2k4** [comment]
Hi Bernhard,

Thanks for your quick response.
Will give it a try using TAP or bridge interfaces to connect to the nodes.
Will see how to do what we have in the post in fedora.
