### ISSUE TITLE
A working PPA for Ubuntu 20.10 which users can use to install GNS3-server.

### ISSUE THREAD

**Issue by PranavBhattarai** [GNS3/gns3-server#1846]
![Screenshot from 2020-11-27 20-45-39](https://user-images.githubusercontent.com/32763112/100495462-3a5be380-3174-11eb-842a-874e39ee84f3.png)
After reading that, I manually installed **dynamics**, **x11vnc** & **xvfb** separately using `sudo apt install <package-name>` command. But I couldn't install **ubridge** as u can see:
![Screenshot from 2020-11-28 12-25-27](https://user-images.githubusercontent.com/32763112/100495553-d38afa00-3174-11eb-9e2a-5dfd9c0057b5.png)
It would be nice to see a PPA working as mentioned in the [official GNS3 website](https://docs.gns3.com/docs/getting-started/installation/linux/).

**Comment by b-ehlers** [comment]
Only the gns3-gui and gns3-server packages were build for groovy, the other packages are missing.

Ubuntu states in <https://ubuntu.com/about/release-cycle>:
> An estimated 95% of all Ubuntu installations are LTS releases.

Since supporting the intermediate releases generates a lot of extra work  I propose to support only the Ubuntu LTS releases with the PPA. For the interim releases a pip-based installation could be added to the documentation in <https://docs.gns3.com/docs/getting-started/installation/linux>.

**Comment by PranavBhattarai** [comment]
@b-ehlers That's really sad news.

"supporting the intermediate releases generates a lot of extra work", I wonder what kind of extra workload it requires.
I always thought **IF** the new LTS release (like 20.04) release supports something, there won't be much of a problem with its upcoming non-LTS (i.e 20.X series because basically everything is the same). Maybe I'm wrong.

[Someone is packaging snap for GNS3.](https://github.com/GNS3/gns3-gui/issues/2912) I think it would be a good idea to support non-LTS users until that happens. _Even though I don't like Snap, at least I will have a reasonable alternative to switch._

**Comment by b-ehlers** [comment]
@PranavBhattarai I don't speak for the GNS3 organization. My suggestion to limit GNS3 packages to the LTS releases is just my personal pont of view. I have no idea, what the GNS3 devs are thinking about that, lets wait for their comment.

**Comment by PranavBhattarai** [comment]
@b-ehlers You mentioned: 
>   An estimated 95% of all Ubuntu installations are LTS releases.

If I understand it correctly 95% of Ubuntu's "installations" are LTS. Why would anyone install a non-LTS for the first time!? Of course, they would install an LTS release. But this doesn't mean that only 5% are non-LTS users, does it? Since the Canonical statement is **only** pointing to the number of installations, NOT the number of LTS users and the number of non-LTS users.

**Comment by grossmj** [comment]
> Since supporting the intermediate releases generates a lot of extra work I propose to support only the Ubuntu LTS releases with the PPA. For the interim releases a pip-based installation could be added to the documentation in https://docs.gns3.com/docs/getting-started/installation/linux.

Actually, this isn't too much work since our PPA package building system is mostly automated and relies on Docker images. I have added the missing packages for Groovy now. 

https://launchpad.net/~gns3/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=groovy

Only VPCS couldn't be built because of some compilation/linking errors:  https://launchpadlibrarian.net/509092156/buildlog_ubuntu-groovy-amd64.vpcs_1%3A0.6.2-1~groovy1_BUILDING.txt.gz

**Comment by grossmj** [comment]
I have released a new vpcs version and pushed on the PPA. Everything should work now. Please comment back if you see a problem. Thanks.
