### ISSUE TITLE
macos big sur, gns3server & fusion 12 issue

### ISSUE THREAD

**Issue by Salombo** [GNS3/gns3-server#1868]
Hi,

I've been having an issue with gns3 on my mac since the big sur update.
I'm not able to start any vm from the gns3 gui/web interface, always having the "no vmnet available between vmnet2 and vmnet99".
After some searches, i've been able to, i think, identify what the issue is but i'm not an expert on gns3 so i'll let you consider what i've found and maybe find a way to fix it. I've been adding some debugs to identify what was going on in the vmware module of gns3. I found out that the function _get_vmnet_interfaces_ubridge() is not able to retrieve any vmnet with the way it tries to find it, always returning an empty array then. 

I started looking at how fusion 12 is working on the interfaces side. Basically, when i'm setting up vmnets it does not affect my interfaces. New interfaces are created when i'm starting a new vm, interfaces names starting from bridge100 to bridge101 etc.. I guess that's why in its current state, the vmware module of gns3 isn't able to identify any vmnet.

However i'm kinda surprised that it seems like noone said anything about it, maybe i'm doing something wrong that's why i highly hesitated to create an issue but i'll take any advice you can give me to maybe fix that.

I don't know if you need more than what i said but i'll answer if you need anything else.

Thanks for your answers

**Comment by grossmj** [comment]
Please try to add more vmnet interfaces. You can do it using the desktop ui in Preferences -> VMware -> Advanced Local Settings

![Selection_009](https://user-images.githubusercontent.com/4752614/109443069-8a0abd80-7a89-11eb-9b33-6be202c631f5.png)

**Comment by Salombo** [comment]
This is the first thing i tried to do, both with the desktop ui and the gns3vmnet cmd. I've created many vmnet ranges from 2 to 100, 2-10, 2-50, 2-99, 10-99 and no change to the issue.

In december i created a thread on the gns3 website with some screenshots: https://www.gns3.com/community/featured/gns3-fusion-12-on-macos-big-sur

**Comment by grossmj** [comment]
I confirm something is broken on macOS Big Sur with Fusion 12 because the virtual network adapters are only created when you powered on a VM... Also, it appears that bridge10X interfaces are created instead of the vmnet ones, and this number X is chosen linearly. Well, thanks whoever decided this, our life if a little bit more complicated now...

Currently GNS3 expects that vmnet interfaces are present before any VM is powered on: https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/vmware/__init__.py#L329L331

We will need to investigate this more.

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/pull/1913 since v2.2.22
