### ISSUE TITLE
Can not config Router via web console

### ISSUE THREAD

**Issue by sada45** [GNS3/gns3-server#1879]
Hey!
    I have run the gns3-web-ui but I can not use `config t` command to config my router and it returns "Invalid input". Also everytime I add a new router, it asks me to "enter the initial configuration dialog", which is different to the the local GNS3. The IOS image I'm using is c3745 and it works fine on my local GNS3. Is there some configuration mistakes or it is a bug? The setting and the error are shown as blow:
<img width=50% src=https://user-images.githubusercontent.com/49777976/112487283-913a9800-8db7-11eb-8fad-63af9bf719d8.png>
<img width=50% src=https://user-images.githubusercontent.com/49777976/112487309-95ff4c00-8db7-11eb-84f2-3f41e77c66d5.png>
<img width=50% src=https://user-images.githubusercontent.com/49777976/112487344-9b5c9680-8db7-11eb-8338-01653782a311.png>
<img width=50% src=https://user-images.githubusercontent.com/49777976/112487381-a0214a80-8db7-11eb-820a-2d4734e5f24c.png>
<img width=50% src=https://user-images.githubusercontent.com/49777976/112487459-ae6f6680-8db7-11eb-8b3b-6c3014ca8a01.png>
<img width=50% src=https://user-images.githubusercontent.com/49777976/112487381-a0214a80-8db7-11eb-820a-2d4734e5f24c.png>
<img width=50% src=https://user-images.githubusercontent.com/49777976/112487478-b29b8400-8db7-11eb-8d8a-3abcec8e9257.png>
<img width=50% src=https://user-images.githubusercontent.com/49777976/112487507-b9c29200-8db7-11eb-9db5-37830758af50.png>
<img width="704" alt="屏幕截图 2021-03-25 220944" src="https://user-images.githubusercontent.com/49777976/112564130-a514e700-8e15-11eb-94c3-414255898f90.png">

By the way, once I use the "Web Console", there is a blank under the console pops up and down when I move the mouse. It seems like a UI bug for me.
![20210325-222217_李烨明_李烨明发起的视频会议_video (1) (1)](https://user-images.githubusercontent.com/49777976/112564777-d5a95080-8e16-11eb-986d-9ebe534f9a79.gif)
Thanks very much!

**Comment by b-ehlers** [comment]
The Web UI sometimes behaves slightly different to the "normal" GNS3 GUI, what causes some irritations. In your case the Web UI creates a dynamips template without setting the "Initial startup-config" in the general settings. The GUI by default sets the initial startup-config to "ios_base_startup-config.txt". Therefore a dynamips device created from a template, that is created within the Web UI, starts without a startup config and therefore runs into the initial configuration dialog. Furthermore it doesn't automatically enter the enable mode, therefore "config t" doesn't work. You have to enter enable mode before, by using the "enable" command.

There are two ways to handle this:
1. Create the templates in the GUI, then the initial startup-config is automatically filled.
2. Modify the template in the Web UI: In the general settings set the "Initial startup-config" to "ios_base_startup-config.txt".

I can't comment about the blank space below the console, because I don't have that issue.

Furthermore I suggest to create this issue in the GNS3/gns3-web-ui repository, as the Web UI developers are working within that repository.

**Comment by sada45** [comment]
It works! Thank you very much @b-ehlers. I'll create issuse in gns3-web-ui for the UI problem.
