### ISSUE TITLE
gns3-server & gui: add Python 3.9 and 3.10 support

### ISSUE THREAD

**Issue by mm1ke** [GNS3/gns3-server#1897]
Hi,

I'm asking if it's possible to add Python 3.9 and 3.10 support?
Even though python 3.10 is still pretty new it would be nice to have it.

Regards,
Michael

**Comment by b-ehlers** [comment]
Why do you think, that GNS3 is not running with Python 3.9? I'm using GNS3 with Python 3.9 since early this year without any issues.

![GNS3_python_3 9](https://user-images.githubusercontent.com/49040325/118356419-7396dd00-b575-11eb-9b41-a64f295439d8.png)

If you have any issues running GNS3 with Python 3.9 you should tell the devs, otherwise it can't be fixed.

**Comment by mm1ke** [comment]
Hi,

`setup.py` only list python until 3.8, which is why i had the impression it might not work with 3.9. To be honest, i haven't tried it yet, but it would be nice to have it official supported.

**Comment by grossmj** [comment]
We will add Python 3.10 after the first public release.
