### ISSUE TITLE
512 IOU limit node 

### ISSUE THREAD

**Issue by rstani** [GNS3/gns3-server#2015]
Hello

Is it possible to bypass the 512 node limitation for IOU devices?

"Error while creating node from template: Cannot create a new IOU node (limit of 512 nodes across all opened projects using the same computes)"

thank you

**Comment by grossmj** [comment]
Sorry, this is currently not possible. IOU itself requires an application ID between 1 and 1024 but we have a limit of 512 per server in GNS3 because we have one uBridge process for each IOU node, uBridge is the what we use under the hood to allow communication with other nodes.

We could eventually support 1023 nodes if we drop uBridge in favor of Linux bridges but this won't happen soon. So for now you will have to use more computes if you want to run more IOU nodes.
