### ISSUE TITLE
Telnet to Devices on Mac OS

### ISSUE THREAD

**Issue by Yuval711** [GNS3/gns3-server#2029]
Telnet to Devices on Mac OS

Does GNS3 developers have any plans to fix the telnet issue to appliances that stated with Big Sur?? I have been told to wait to the next GNS3 version or to wait for the new MAC OS update.... in the mean time, I'm on MacOS Monterey and GNS3 2.2.29 with paid version of Fusion and ..... still not working!
I have uninstalled, reinstalled, changed this setting, changed that settings but to no avail

Are there any plans at all to fix this??

**Comment by jnatschev** [comment]
have you tried removing (backing up) your existing gns3 configuration files and starting the gns3 gui as if it was newly installed so the configuration files a created brand new?
i can't remember where the configuration files are located on disk exactly. try "$HOME/.config/GNS3/2.2".
so, perhaps:
1. quit the gns3 gui, if it is running;
2. rename the "2.2" directory to "2.2.backup";
3. start the gns3 gui;
4. run through the configuration items;
5. open your project;
6. start a device;
7. test telnet to the device

just a thought...

my setup is:
- MacOS Big Sur
- VMware Fusion 12.x
- GNS3 VM 2.2.29 (GNS3 Server 2.2.29)
- GNS3 GUI 2.2.29 or GNS3-Web-UI 2.2.29
Everything runs on the GNS3 VM. The GNS3 GUI is purely for GUI access to the GNS3 VM based GNS3 Server.
No issues with telnet access to topology devices (including docker containers).

**Comment by Yuval711** [comment]
Q. Have you tried removing (backing up) your existing gns3 configuration
files and starting the gns3 gui as if it was newly installed so the
configuration files are created brand new?
A. Yes, I have done it before many times when it was suggested in the past
and the issue still persists. But just for kicks.... I did it all again.
""Luckily"" I already lost ALL my projects from previous attempts to
correct the issue so I had not thing to back up.


   - Uninstalled GNS3 completely from my MAC
   - Deleted the VM (with all the appliances that were on it)
   - In "$HOME/.config/" I deleted the GNS3 folder and it's content.
   - Re-installed GNS3 version 2.2.29
   - Re-installed GNS3 version 2.2.29
   - Allocated 4 CPU's with 8192mb of RAM
   - Imported all new appliances (Cisco IOSv, Cisco CSR1000v, ASAv)
   - Allocated proper CPU and RAM to each


Nothing works. cannot telnet to anything and cannot VNC to the ASA. This
was all working great before BigSur. I had plenty of projects and was able
to telnet to all devices.

Still getting stuck on all appliances on this:

Trying 172.16.252.128...
Connected to 172.16.252.128.
Escape character is '^]'.

I am using:
MAC OS Monterey
VMware Fusion Player Version 12.2.1 (18811640)
GNS3 VM 2.2.29 (GNS3 Server 2.2.29)

There is still no fix in a MAC. nothing works!!

Yuval

**Comment by jnatschev** [comment]
apologies, i can't be of more assistance. i've been using the GNS3 suite for a long time now and have not experienced this issue.

**Comment by Yuval711** [comment]
this is very disappointing response. Is there anyone else that can help? any other avenue I can follow? I initially posted this issue in the GNS3 community board and was directed here under the premise that the developers may be able to assist. But a response like such (... it works for me therefore it's good.) is not a professional response. The effort that was put in the attempted solution was not very intuitive rather only a list of how it works on your machine. I saw many users on the community board that have that same exact issue. 

Kindly direct me to someone who can try to assist or let me know if I should just move on to another product. I did not invest money in getting Viral Images, VMware fusion to fail with your product.

**Comment by grossmj** [comment]
Sorry developers have been away and unable to answer. Please can you include screenshots of the problem if relevant. Thanks 👍

**Comment by jnatschev** [comment]
@Yuval711, i apologise my response caused you disappointment. i assure you i had no ill intent.

firstly, my message did not say "...it works for me therefore it's good." what my message said is that i, as a gns3 user, have not experienced the issue on a platform that is similar to yours.

secondly, i am not a gns3 developer. i am a gns3 user. a user that experiences gns3 issues from time to time and uses the gns3 tools, like github (here), to report and find answers/solutions. as such, you got a well intentioned gns3 user response.

as a member of the gns3 community, i have "invested" time in an attempt to get you (and in the past others like you) moving forward by trying to replicate the issue you reported. unfortunately, i was unable to replicate the issue.

i, too, have invested "money" and effort in gns3. the reason i participate is because if i get someone moving forward using my experience of gns3 (even though limited knowledge of gns3), then this issue you lodged is one less issue for the "developers" to address and keeps them focused on "developing"; hence community.

as you will see now, one of the developers has responded to your issue and they will endeavour to sort out your issue; just like they have for so many gns3 users.

**Comment by cristian-ciobanu** [comment]
I assume this issue is the same or similar with the one reported here https://github.com/GNS3/gns3-server/issues/1619 and it's not replicated unless you run a remote GNS3 server or GNS3VM and leave the topology running for some time.
There is a workaround which is implemented in version 3.0 and I asked the developers if this can be backported to release 2.2.x until a permanent fix is released.

**Comment by Lugib** [comment]
Hello,

I just want to contribute here to the community.
I've been struggling with this. When tyrying to open a console of a device with the default gns3 parameters on my macbook air m3 I got the following message:

**"zsh: bad CPU type in executable: telnet"**

I just asked chatGPT (I know...crazy...) and followed the instructions:

1) Install telnet from "brew":
https://mac.install.guide/homebrew/3

2) Modify the console script by the one provided by chatgpt which uses the complete path for telnet:
**osascript -e 'set posix_path to do shell script "echo \"$PATH\""' -e 'tell application "Terminal"' -e 'activate' -e 'do script "echo -n -e \"\\033]0;{name}\\007\"; clear; PATH=" & quoted form of posix_path & " /opt/homebrew/bin/telnet {host} {port} ; exit"' -e 'end tell'**

Now works like a charme... I hope it helps someone....

**Comment by grossmj** [comment]
Thanks, we have replaced the telnet binary shipped in the GNS3 app by a universal one. This should make things work without having to do your workaround.

**Comment by Lugib** [comment]
> Thanks, we have replaced the telnet binary shipped in the GNS3 app by a universal one. This should make things work without having to do your workaround.

In which version?

**Comment by grossmj** [comment]
In our latest version, 2.2.49

**Comment by Lugib** [comment]
> In our latest version, 2.2.49

I just installed in and tested in a new macbook air m2 and it's still the same... I guess I'll have to do my workaround...
That being said, I am using a remote server, not a local VM, maybe that changes something

**Comment by grossmj** [comment]
I am going to get access to a mac with Apple Silicon soon so I can test on my side.

**Comment by grossmj** [comment]
@Lugib this should work in v2.2.50

If not, please can you check the telnet binary supports both x86 and arm using this command?

`lipo -archs /Applications/GNS3.app/Contents/MacOS/telnet`

Thanks 👍
