### ISSUE TITLE
qemu process crashes, return code 6

### ISSUE THREAD

**Issue by neilspage** [GNS3/gns3-server#2037]
Hi,

So I run VSRXs in GNS3, though they crash after a while of booting up.

```

QEMU process has stopped, return code: -6

Start QEMU with /bin/qemu-system-x86_64 -name vSRX20.4R1-3 -m 6144M -smp cpus=2,sockets=1 -enable-kvm -machine smm=off -boot order=c -drive file=/opt/gns3/projects/792a193e-90b9-4d05-a1fa-548273cf8fa4/project-files/qemu/c2ab16db-890e-472b-86f7-6b33cb32bcce/hda_disk.qcow2,if=ide,index=0,media=disk,id=drive0 -uuid c2ab16db-890e-472b-86f7-6b33cb32bcce -serial telnet:127.0.0.1:5005,server,nowait -monitor tcp:127.0.0.1:44239,server,nowait -net none -device vmxnet3,mac=0c:ab:16:db:00:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:20037,localaddr=127.0.0.1:20036 -device vmxnet3,mac=0c:ab:16:db:00:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:20039,localaddr=127.0.0.1:20038 -device vmxnet3,mac=0c:ab:16:db:00:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:20041,localaddr=127.0.0.1:20040 -device vmxnet3,mac=0c:ab:16:db:00:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:20043,localaddr=127.0.0.1:20042 -device vmxnet3,mac=0c:ab:16:db:00:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:20045,localaddr=127.0.0.1:20044 -device vmxnet3,mac=0c:ab:16:db:00:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:20047,localaddr=127.0.0.1:20046 -display none -smp 2 -cpu host



Execution log:

qemu-system-x86_64: /build/qemu-0Dw8aG/qemu-4.2/hw/net/vmxnet3.c:1423: vmxnet3_activate_device: Assertion `VMXNET3_MIN_MTU <= s->mtu && s->mtu < VMXNET3_MAX_MTU' failed.

```

I have tried adding the "-cpu host" flag, disabling MTU check on ESXI with (esxcli system settings advanced set -o "/Net/Vmxnet3NonTsoPacketGtMtuAllowed" -i 1).

I have also ensured my port groups are set to the correct version: https://docs.gns3.com/docs/getting-started/installation/esxi/

Currently my client and GNS server are on 2.2.31 (latest version).

**Comment by neilspage** [comment]
@grossmj I see you added it to a milestone, what does tis mean? :o

**Comment by grossmj** [comment]
It means I am going to review it before the next release. Regarding the issue, I am not sure what the workaround could be, maybe upgrading Qemu would help?

**Comment by neilspage** [comment]
@grossmj thank you for your hard work, I hope GNS3 isn't a one-person project because it seems like a lot of work :)

**Comment by atn-79** [comment]
i have the same error. I have using 2.2.18 over an year and vSRX have been working fine until this week need to to some testing with vSRX -> vSRX is booting ok but almost instantly after that vSRX crash with these errors:

qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-system-x86_64: /build/qemu-0Dw8aG/qemu-4.2/hw/net/vmxnet3.c:1423: vmxnet3_activate_device: Assertion `VMXNET3_MIN_MTU <= s->mtu && s->mtu < VMXNET3_MAX_MTU' failed.

tried these:

upgraded GNS3 client and VM 2.2.18 -> 2.2.31 -> doesn't help

1. added -cpu host with vSRX template -> doesn't help -> removed this change
2. changed hdd ide ->sata -> doesn't help ->this change i keeped because vSRX boots faster with this setting.
3. changed network adapter vmxnet3 -> e1000 -> this change looks like working -> vSRX havent crashed yet (1h).

**Comment by grossmj** [comment]
Looks like the problem comes from Qemu. Do you know if the version of Qemu has been updated?

**Comment by atn-79** [comment]
Sorry, i don't know that. 

that e1000 interface doesn't look very promising. Ping works time to time but not all the time.
 vSRX if <-> client

**Comment by atn-79** [comment]
changed vSRX networktype to paravirtualized network I/O (virtio-net-pci) -> this looks like workingwhen tried to ping vSRX to vSRX and vSRX to client.

**Comment by josephmhiggins** [comment]
Okay.....
So...

1.  to find out what should be used with a vm, you right click on the vm's .gnsa file and open it with a text editor
2. you scroll down to the "documentation_url" key
3. you read the value of the key
4. for juniper vsrx, it says "http://www.juniper.net/techpubs/",
5. then you have to hope the OEM did not move the website
6. then if the website is valid, you have to try to find your way to the documentation for your particular VM from the OEM
7. then in the .gnsa file, you have to compare what someone set the value of the key "adapter_type" versus what the OEM says the vNic should be set to
8. for juniper vsrx, juniper says it should be virtio
9. there is no explicit 'virtio' network adapter type in gns3,  but the closest seems to be virtio-net-pc
10. i do not know what the difference is between either virtio and virtio-net-pc or vmxnet3

But, I would say to ask whomever built that juniper .gnsa file why they chose vmxnet3 instead of virtio-net-pc
for the juniper .gnsa file.

As far as what qemu binary to use, this is popping up lately.
I recommend using whatever the gns3 team set the qemu binary to use in the .gnsa file

That being said, I spent 8 hours learning and installing qemu 6.2.0 in a brother companion to my
GNS3 VM 2.2.31, GNS VM 2.2.31 EXP

EXP stands for experimentatl.

I am not a native ubuntu user.
My skill level with ubuntu is that of a child.

**Comment by josephmhiggins** [comment]
So...
it gets more complicated.
The juniper supports either "virtio" or "sr-iov", e.g. _not_ e1000, _near as I can tell_
SR-IOV is cutting edge.
I have a cutting edge server with ESXi 7.0
But, my cutting edge server default to e1000 over SR-IOV
My VMware books all like SR-IOV versus vmxnet3
But, my cutting edge server is for a home lab.
So...I would probably research the choice of sr-iov or vmxnet on anything brezular, marc weisel, or ehlers had on their websites for network settings for my home lab server.
I do not think I would want to bother the gns3 developers over that choice.

**Comment by sfer22** [comment]
I was experiencing the same problem, but after upgrading qemu from version 4.2.1 to 5.0.0, the issue cleared and vSRX is working again. So definitely qemu related. I am using GNS3 version 2.2.32, vSRX with vmxnet adapters. Hope that helps.

**Comment by davehouser1** [comment]
@grossmj, the process you shared did not fix the issue for me. I would like to upgrade qemu manually to see if that helps.
@ster22, can you please share the process you followed to perform the upgrade of qemu on gns3? Also did you upgrade anything else or just qemu? Please include any dependencies you needed to install in your process, and if you compiled form source which options you used for `./configure`

**Comment by mlf-inde** [comment]
I was experiencing the same issues, and after reading these comments I changed the network type to `Paravirtualized Network I/O (virtio-net-pci)` after doing this my vSRX stopped crashing and has been working fine. For me it was a new install of vSRX that never worked (not an existing device that suddenly stopped working)

My environment:
Windows 11, vSRX 20.3R1, GNS3 VM in Hyper-V, GNS3 v2.2.33.1. QEMU = whateer version got installed by default with GNS3 2.2.33.1
