### ISSUE TITLE
Virtualized Intel VT-x/EPT is not supported on this platform.

### ISSUE THREAD

**Issue by SpockIsCoding** [GNS3/gns3-server#2164]
My processor: Intel(R) Core(TM) i5-12500H 

error:

![image](https://user-images.githubusercontent.com/97816800/212410257-c304923b-1221-4f77-be1c-21bcae2158cd.png)

**Comment by cristian-ciobanu** [comment]
You might have Hyper-V enabled which might cause this error. Please check and if it is enabled turn it off.
Please see this post for more details. https://communities.vmware.com/t5/Nested-Virtualization/Virtualization-Intel-VT-xEPT-it-not-supported-on-this-plataform/m-p/2284582/highlight/false#M2608

**Comment by SpockIsCoding** [comment]
@cristian-ciobanu I followed all tutorial, I did all mofifications to solve that probem but it remain the same

**Comment by eantowne** [comment]
@SpockIsCoding Have you tried all of the steps listed [here](https://www.gns3.com/community/featured/fixing-vt-x-or-amd-v-not-available-in-windows-11-with-vmware-ws-pro-and-player)?

Assumption: Windows 11, VMware WS/Player (hopefully 17)

It is important to:

1. Ensure that Virtualization is enabled in your BIOS (check if Task Manager->Performance->CPU show that virtualization is enabled)
2. Uninstall VMware WS/Player
3. Reboot
4. Follow the instructions in the tutorial linked [above](https://www.gns3.com/community/featured/fixing-vt-x-or-amd-v-not-available-in-windows-11-with-vmware-ws-pro-and-player)
5. Reboot
6. Install VMware WS/Player, when installing, it should not ask you any questions about "Hyper-V Mode", if it does, you missed something in the steps above
7. reboot

**Comment by SpockIsCoding** [comment]
![image](https://user-images.githubusercontent.com/97816800/212580490-54c7c723-5c56-4346-aec1-942ab6ce1e1d.png)

now works!!! thankyou.

**Comment by eantowne** [comment]
Glad I could help!

**Comment by dll21** [comment]
works for me as well thank you ! @

**Comment by onurmicoogullari** [comment]
I had already followed all the steps, except for re-installing VMWare Player, and it still failed. But that one did the trick for me. Thanks @eantowne!

**Comment by alfredwongpy** [comment]
@onurmicoogullari Same as you, i followed all steps except VMware re-installation.
May I know how did you get it done? What's the trick?

thanks a lot!

**Comment by onurmicoogullari** [comment]
> @onurmicoogullari Same as you, i followed all steps except VMware re-installation.
> 
> May I know how did you get it done? What's the trick?
> 
> 
> 
> thanks a lot!

The re-installation of VMWare Workstation Player did the trick for me. I would suggest following all the steps that @eantowne described.

Hope it helps!

**Comment by alfredwongpy** [comment]
> > @onurmicoogullari Same as you, i followed all steps except VMware re-installation.
> > May I know how did you get it done? What's the trick?
> > thanks a lot!
> 
> The re-installation of VMWare Workstation Player did the trick for me. I would suggest following all the steps that @eantowne described.
> 
> Hope it helps!

@onurmicoogullari 
Many thanks for your reply, let me try and revert! :)

**Comment by alfredwongpy** [comment]
I've followed the steps from @eantowne , still asking about Hyper-V during the VM installation process.
I really don't know what to do..... :(

![圖片](https://github.com/GNS3/gns3-server/assets/77913061/1729fd4d-e259-4bae-b928-38b875bcd251)


![圖片](https://github.com/GNS3/gns3-server/assets/77913061/855f3a59-1721-43e6-86a2-140be9ff7d9b)

**Comment by eantowne** [comment]
Based on that screenshot, something is still enabled, "Hyper-V" or "Device/credential guard" enabled in some form. You will need to resolve that.

**Comment by alfredwongpy** [comment]
> Based on that screenshot, something is still enabled, "Hyper-V" or "Device/credential guard" enabled in some form. You will need to resolve that.

@eantowne  Agree, and that's why I don't know what to do anymore, since I've followed everything steps you provided :(

**Comment by eantowne** [comment]
If that is the case, and you have verified that all of the changes persisted through reboot, then this is a Windows/VMware issue. They are better equipped to provide assistance with their product than the GNS3 development GitHub site would be.

The guide I wrote was based on my own research and experimentation with a Windows system that I installed specifically for the purpose of trying to find a solution. It was also written a while ago, and both Microsoft and VMware may have changed things. I generally do not use Windows (exception being my work laptop, under protest, and my gaming desktop). Everything else I do, is on MacOS or Linux.

**Comment by alfredwongpy** [comment]
Finally I managed to fix the problem by re-installation the whole OS (Windows 11 23H2), except I didn't install the driver related to Drive Guard.

The VMware workstation is perfect now.
Thanks everyone.

**Comment by alfredwongpy** [comment]
![圖片](https://github.com/GNS3/gns3-server/assets/77913061/c389ba2a-aa52-4b91-b0de-82cf54f07a56)
I am now able to run nested VMs inside ESXi8 :)

**Comment by grossmj** [comment]
Perfect, thanks for the update 🙂

**Comment by alfredwongpy** [comment]
Again, thanks all for the comment! :)

![圖片](https://github.com/GNS3/gns3-server/assets/77913061/2503839d-897c-464c-9409-88b9f143aac4)

![圖片](https://github.com/GNS3/gns3-server/assets/77913061/c77c78c2-8c1b-47eb-abb4-7e3984a86231)

**Comment by Trailingslashes** [comment]
bcdedit /set hypervisorlaunchtype off

**Comment by rene-mas** [comment]
Just want to document the solution that worked for my, since I had the same problem as mentioned above and nothing that was mentioned earlier helped for me. Very helpful in resolving the issue was the System Information msinfo32.exe tool - since it showed that the "Device Guard Virtualization based security" was still Running and that "A Hypervisor has been detected..". I tried many things to fix this in order to disable VBS Virtualization Based Security and the Credential Guard and whatever instructions where there in various forums worked for me, but had somehow no effect. Finally I stumbled accross the last answer from human_rosas in [this post](https://superuser.com/questions/1702207/hypervisor-detected-unable-to-uninstall-hyper-v-on-windows-11-windows-surface) which gave the hint: Run a script provided by Microsoft (DG_Readiness_Tool_v3.6.ps1 -Disable -AutoReboot) to disable VBS and the Credential guard. And it worked like a charm for me. After re-installing VMware Workstation, nested virtualization was just working :)

**Comment by majidfarhadi7** [comment]
@eantowne very very tanks. very nice

**Comment by AnzeuS** [comment]
I have created a guide with a solution that worked for me https://github.com/AnzeuS/Solution-to-Intel-VT-x-EPT-Problem-in-VMware-and-VirtualBox/blob/main/README.md

**Comment by martiprog** [comment]
U have fully resolved the issue. It is a problem with the new version of Windows (24H2) which has made some major changes to the internal architecture for the future of ARM processors. Because of that the old methods don't work. Here is my GitHub repo where I explain how to resolve the issue. Hope this helps:). If you have any questions, feel free to ask.

[Solve virtualization issue with Workstation](https://github.com/martiprog/Solving-Virtualized-Intel-VT-x-EPT-is-not-supported-on-this-platform-GNS3-Issue)
