### ISSUE TITLE
Cannot reopen console

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#2182]
Some users have reported that they cannot reopen consoles: https://gns3.com/gns3-2-2-37-released. This problem seems to come from this commit https://github.com/GNS3/gns3-server/commit/1148dbc48e6703e757d7286f39ee28da7e5f1584 because users reported that eveything is working well in v2.2.35.1

"I can open a console session to a device, but if I close my console session then attempt to reopen it,  putty is unresponsive until I power cycle the network device. Same behavior on IOU images and VIOS images.  IOS images appear to be unaffected."

**Comment by grossmj** [comment]
Note to myself: the new telnetlib3 could be used to refactor how we handle telnet consoles https://pypi.org/project/telnetlib3/

**Comment by josephmhiggins** [comment]
I strongly suspect the web-ui aspect of gns3 is interfering with the gnui aspect of gns3.
I had to abridge, e.g. delete 1/2 of my post here:
https://gns3.com/community/featured/troubleshooting-design-for-windows-and-vmware-adapters-ver3
because my instructions were to delete the not-running wireshark capture and I ended up with
unable to delete a link between the gns3 cloud appliance and the gns3 ethernetswitch appliance - AND
please note I was not running the web-ui and I was not running the gns3server in debug mode.
This inability to delete the link forced me to kill gns3 in task manager
If I was running the gns3server in debug mode, _maybe_ I could have seen something
I "always" run gns3 with the gns3server in debug mode now.

I already know that the web-ui and the gui are not in sync when it comes to wireshark, but I let it slide because gns3 3.0 is just around the corner.

Please note that Glenn wrote:
"Just an additional note.  It does this on the GUI.  WUI does not have this issue."

**Comment by grossmj** [comment]
https://github.com/GNS3/gns3-server/commit/30c85703c8f3b6cace64628ee182bf03084babf1 fixed the problem
