### ISSUE TITLE
GNS3 and Wireshark issue

### ISSUE THREAD

**Issue by Rekano33** [GNS3/gns3-server#2259]
Hi everyone, help me solve a small problem.

The problem is that when I stop and restart traffic collection in wireshark I get the error "wireshark portable data written to the pipe is neither in a supported pcap format nor in pcapng format.". (attached screenshot).
[
![2023-07-24_17-24](https://github.com/GNS3/gns3-server/assets/99503253/c4132868-5efc-451c-baec-9d2a1e15d691)
](url)

This error appears only when using wireshark in GNS3. If you use wireshark separately, this problem does not occur.

To solve the problem, I need to close the wireshark window completely and recapture the line between the two devices. 

OS: linux Mint  "21.1 (Vera)"
OS: Ubuntu 22.04.2 LTS
Wireshark 4.0.6 
GNS3 2.2.41

**Comment by grossmj** [comment]
I don't think you can stop and restart the traffic collection in Wireshark because it reads packets on stdin (for details, the command we use is `tail -f -c +0b <pcap_file> | wireshark -o "gui.window_title:<window_title>" -k -i -` and there is more info on https://wiki.wireshark.org/CaptureSetup/Pipes). To solve this, the source would have to send a new libpcap header but GNS3 cannot know you restarted traffic collection in Wireshark.

![Image](https://github.com/GNS3/gns3-server/assets/4752614/538fc72d-2ab3-4900-b026-8df9eb38a21a)

Maybe you can consider using the traditional capture method but you will have to reload the file manually in Wireshark.

![Image](https://github.com/GNS3/gns3-server/assets/4752614/ce438777-af3b-40ab-a795-65dd95d7f58b)
