### ISSUE TITLE
The IOU image has been uploaded to the compute node, but is not in the IOU image list

### ISSUE THREAD

**Issue by yaolin1998** [GNS3/gns3-server#2376]
![QQ截图20240507003747](https://github.com/GNS3/gns3-server/assets/35018520/6cfe400c-04e1-465f-9ff5-65d44e36fd56)

**Comment by grossmj** [comment]
@yaolin1998 thank you, we will look into it. Please can you share the image with us? Our email: developers@gns3.net thanks!

**Comment by cristian-ciobanu** [comment]
The IOU image is the latest one provided by the CML 2.7 platform. I saw this issue also. 
The IOU image is not detected properly as an IOU image. The workaround is to select from the file type list All files instead of the IOU image and then it will display all files in the current folder including existing IOU images. 
I guess since the new IOU images are IOS-XE based something has changed and the current detection method  is not compatible anymore.

**Comment by grossmj** [comment]
@cristian-ciobanu thank you confirming what I was suspecting. Please can you send me this image so I can change the detection method? Thanks 👍

**Comment by yaolin1998** [comment]
> 谢谢，我们会调查的。请您能与我们分享借条图片吗？我们的电子邮件：[developers@gns3.net](mailto:developers@gns3.net) 谢谢！

OK, I will send it to you later using gmail

**Comment by grossmj** [comment]
Thanks a lot, I got them.

**Comment by grossmj** [comment]
@yaolin1998 how have you uploaded the IOU image?

**Comment by yaolin1998** [comment]
@grossmj I have tried both curl and gns3-gui, and both methods have the same effect

**Comment by grossmj** [comment]
@yaolin1998 I fixed the bug. Thanks for catching this 👍
