### ISSUE TITLE
Unable to Create Links

### ISSUE THREAD

**Issue by astoffel** [GNS3/gns3-server#265]
My current setup is a windows machine running the GNS3 gui and everything else running on a remote server setup in the lab.

When trying to create a link a get this error. (NOTE: this only happens sometimes)

![gns3_linkbug](https://cloud.githubusercontent.com/assets/8586296/8656151/c31c04f8-294a-11e5-92fb-dfe482bb1e36.png)

It turns out I have webmin running and uses port 10000, I was wondering if there is a way to change the default "starting" port on the remote server (a config file?) or maybe make a way for the GUI to push that information to the server.

**Comment by grossmj** [comment]
Hi,

You can create ~/.config/GNS3/gns3_server.conf (if it doesn't exist already) on the server.

and add the following lines to have a range from 11000 to 20000 for instance.

```
[Server]
udp_start_port_range = 11000
udp_start_end_range = 20000
```

**Comment by astoffel** [comment]
Ty..working now

**Comment by grossmj** [comment]
I need to investigate this because it should not happen since we check if a port can be used before we use it.

**Comment by grossmj** [comment]
Ok, I understand what went wrong.

In Python we check that a port is available by basically doing this:

```
import socket
host = "127.0.0.1"
port = 10000
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind((host, port))
```
This works even if another socket has been bound with another address and same port but Dynamips and VPCS do not specifically bind a host:

```
sck = socket(AF_INET, SOCK_DGRAM, 0))
memset(&sin,0,sizeof(sin));
sin.sin_family = PF_INET;
sin.sin_port = htons(local_port);
bind(sck,(struct sockaddr *)&sin, sizeof(sin))
```
Bind fails with "Address already in use". The following line is needed otherwise the bind is successful in GNS3 but not in Dynamips or VPCS:

```
sin.sin_addr.s_addr = inet_addr(local_host);
```
So we have 2 solutions, "fixing" Dynamips and VPCS (and potentially more programs) .... or just use "0.0.0.0" when checking for available UDP ports. Not the cleanest but clearly the easiest method I think.
