### ISSUE TITLE
.vmwarevm are not seen in the server list

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#313]
If you try to use modernie you get VM has .vmwarevm. And you don't see them in the VM list.

**Comment by grossmj** [comment]
What is modernie?

**Comment by ehlers** [comment]
I assume, Julien means https://dev.modern.ie/tools/vms/, where you can download VMs for testing IE. They also are useful as a quick way to add a windows VM.

I can reproduce it on my Mac, when I download a VMware VM (I used IE6 on XP) into the Downloads folder, unzipped it there and then dragged the resulting IE6 - WinXP.vmwarevm into VMware Fusion. That way the VM is not installed in the normal VM folder, but stays in the Downloads folder (not really recommended).

When I now try to add this VM in the GNS3 VMware wizard, this VM is not shown in the list. The reason is that the inventory_path is wrong for OS X, therefore GNS3 looks into the normal VM directory, where the IE VM is not installed, therefore not found.

Fix:
```
diff --git a/gns3server/modules/vmware/__init__.py b/gns3server/modules/vmware/__init__.py
index 839ecee..d54bb61 100644
--- a/gns3server/modules/vmware/__init__.py
+++ b/gns3server/modules/vmware/__init__.py
@@ -465,7 +465,7 @@ class VMware(BaseManager):
         if sys.platform.startswith("win"):
             return os.path.expandvars(r"%APPDATA%\Vmware\Inventory.vmls")
         elif sys.platform.startswith("darwin"):
-            return os.path.expanduser("~/Library/Application\ Support/VMware Fusion/vmInventory")
+            return os.path.expanduser("~/Library/Application Support/VMware Fusion/vmInventory")
         else:
             return os.path.expanduser("~/.vmware/inventory.vmls")

```

**Comment by noplay** [comment]
Good catch !
