### ISSUE TITLE
Idea: Version control for GNS3 projects

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#375]
I don't know if the idea is worthy:
It could be useful to have some kind of version control for GNS3 projects (text files).
 - Variant 1: Keep track of GNS3 topology (only .gns3 file)
 - Variant 2: Keep track of entire GNS3 project including text-based configuration devices (Cisco, juniper...)

**Comment by noplay** [comment]
The variant 2 is hard to implement because for most projects we don't have access to the config. For example juniper we just see the memory has a disk image. Perhaps we can use the snapshot features of the emulators.

**Comment by AJNOURI** [comment]
Variant 1: Maybe a simple "undo" / "redo" is more straight forward then version control.
Variant 2: Indeed, snapshot is more appropriate for devices.

**Comment by noplay** [comment]
The problem of 1 is the need to be able to replay all the operations to revert them. But some operation can't be undo. If you delete an appliance the disk is lost and revert it mean you need to be able to recreate the disk otherwise it will not boot.

A solution could be to snapshot the whole project state and be able to revert to it. If we store everything in a zip it's possible to version it with git or Dropbox.

**Comment by AJNOURI** [comment]
Got it. Thanks Julien.
