### ISSUE TITLE
gns3-server doesn't support multiple clients

### ISSUE THREAD

**Issue by anubisg1** [GNS3/gns3-server#42]
As per title. Gns3-server refuses to server multiple clients.

**Comment by networkpadawan** [comment]
you can try with a client per port? gns3server --port=8001 gns3server --port=8002, it starts ok, but don't know what other services are needed to start per client, or if gns3 itself proxies them

**Comment by superwolfboy** [comment]
may be need use database to manage the user id , project id, session id, equipment id and something else...this can be use only one gns3server instance. 
otherwise, at this moment we also can implement  multiple clients without change anything of gns3server, we can make one special "server core.ova", it is a linux image include iou,dynamips, virtualbox and qemu,then deploy on ESXi. copy it to many instance with different ip address , and each "student" can connect each one "server core instance". One 64G RAM server can be used for 10-20 clients.

**Comment by noplay** [comment]
It's done in the branch asyncio. Alpha release coming soon
