### ISSUE TITLE
Docker VM not persistent

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#428]
Every time a project with a docker VM is opened a new container is created and when the project is closed, it is deleted. That means, that changes to that container are available only during an active project. After closing the project the container and all modifications are lost.

One reason might be that the project save and my changes (see https://github.com/GNS3/gns3-gui/issues/1038) don't work properly.

Another possibility is, that it's designed that way.
If that's the case, I propose to not delete the container at project close. On the next open GNS3 can check if the container is still there. If it is, it can use it. Otherwise a new container is created.

**Comment by noplay** [comment]
Did you see that volumes are keep between project closed and open? And the files are in the GNS3 projects.

For me the issues if we do not destroy the container at the end are:
* we will create a lot of garbage in docker and the user will not seen it since it's in the docker folder and not in the GNS3 folder
* people will lost stuff when moving a lab from an host to another since the data is in Docker and not in the GNS3 project. 

Work in progress doc about docker support:
https://docs.google.com/document/d/1KGkv1Vm5EgeDusk1qS1svacpuQ1ZUQSVK3XqJ01WKGc/edit?usp=sharing

But it subject to debate, what could be the less surprising for users.

**Comment by ehlers** [comment]
I haven't tried volumes yet, that's the next point on my list.

I agree with your points. It may create some garbage and especially when docker is run in the GNS3 VM the user has no direct control of the docker VMs. Furthermore you can't easily move/save/restore such a container.

So volumes might be a good way to overcome this issue. But it has to be well documented, otherwise this non-persistence will surprise the user. It least it surprised me.

**Comment by noplay** [comment]
Perhaps we can put a message when you open a console to a docker container.

"Only docker volumes will be persist accross project opening all the other data will be lost"

**Comment by ehlers** [comment]
Maybe it's enough to show this warning only in the docker creation wizard. Having this warning every time you open a console might be too much.

**Comment by AJNOURI** [comment]
Knowing that mounting volumes is a "docker create" option and the container is created when inserting  container device into the topology, maybe we could add a dialog box before inserting the device (before the creation) asking to assign a directory (could contain data previously created by other containers).

**Comment by ehlers** [comment]
Currently GNS3 mounts only volumes, that were defined in the image. I'm totally fine with that, as the creator of an image should know, where external volumes are reasonable. So (personally !!!) I see no reason for adding the possibility to mount an arbitrary directory. Perhaps we can wait with this, until we have some more experience with docker and GNS3.

Another question is, if we want the possibility to define the local directory of the mounts. Currently it's a subdirectory within the project directory. The only reason I currently see for defining another place is, that you want to access the same data volume in different projects. One problem is, that docker runs with root rights and you can overwrite any file and directory when the user can choose any directory. So it's quite dangerous.

Another problem is, that this directory is on the GNS3 server, that has docker installed, normally the GNS3 VM. And we probably don't want the users to define, where the data is going within the GNS3 VM. It should be a black box. So I also would postpone such a function, until we have more experience.

**Comment by noplay** [comment]
I agree it's raise a security issue and create portability problems. If you share a topology from the web you can read the filesystem of the users and send you the data. Even if we are not good at security for the moment we need to think way to improve it.

I see a use case where you can use a non vm directory. A tftp server where you have all the images for PXE boot. A lambda users will want to share the data between all his projects or for a specific projects.

A way to do that could be mount:
* in all containers a directory /gns3/images => linked to your GNS3 images folder
* in all containers a directory /gns3/project => linked to the current project folder (or a subdirectory inside)

From the docker side it's easy to do that, but I'm more concern about the user side. Since images and project folder depends of the server where the container is running it's confusing for the user.

**Comment by noplay** [comment]
But it's more a reflexion we still need more experience with that.

@AJNOURI what is you use case? I know that you hack GNS3 for years in order to use docker ;)

**Comment by AJNOURI** [comment]
Agree with the security implications of broader user access to GNS3 VM. 
We still need to find a compromise if we want to offer data persistence and portability between containers.

For example to avoid container garbage decoupling in the default docker volume directory (/var/lib/docker...), we could customize the volume mapping to a default location inside GNS3 directory, which could be shared by all containers by default (during creation).

ex: docker create -v /GNS3/containers/data:/data

Where /GNS3/containers/data is a directory mapped by GNS3 VM from the host. The user will have to choose the host directory, but not the directory inside GNS3 VM.

Independently of volume mapping, the idea of @ about the possibility of listing and inserting previously created containers is interesting.

I have been doing this (in linux) to avoid the repetitive configuration of GNS3 devices parameters with Cacti and BIND server containers.

**Comment by ehlers** [comment]
What about the following idea:

Currently the data volumes are saved in &lt;gns3 directory&gt;/projecta/&lt;project name&gt;/project-files/docker/&lt;docker-vm-uuid&gt;/ and that stays the default. But in the docker template and node configuration the user can change that to a subdirectory of &lt;gns3 directory&gt;/docker-volumes/ . So even if he enters /etc as local directory it will be stored at &lt;gns3 directory&gt;/docker-volumes/etc .

That way the user has some control about the volume storage place, but it won't break out of the gns3 directory hierarchy. And with a web file browser (see https://github.com/GNS3/gns3-gui/issues/1054) the user can transfer those files onto his local computer.

**Comment by noplay** [comment]
The problem I see with that is the portability of topologies. And potential conflict between two containers.

**Comment by noplay** [comment]
I will close this issue because with volume we solved the persistent problem.

For sharing data between host, at this time I think it's add too much complexity and magic (volume is already confusing for lambda users). If we stick to principle that GNS3 emulate network hardware this concept of share directory doesn't exists. Except if we create a node representing a disk physically attached to multiple node.

**Comment by ehlers** [comment]
OK, I'm fine with that.

**Comment by AJNOURI** [comment]
OK.
