### ISSUE TITLE
GNS3 v1.5: changes in containers do not persist after GNS3 reboot

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#482]
Looks like it is the case for all containers

![gns3-1 5-docker-persistent](https://cloud.githubusercontent.com/assets/1716020/14318953/810879be-fc0f-11e5-8649-239348d87d23.gif)

**Comment by noplay** [comment]
Hi,

It's by design.

Only volumes are persisted. If you want to persists your config in the Dockerfile you need to put the config in a volume.

If in the Dockerfile the container mount volumes. GNS3 will create in the project folders a folder for each Docker volume and will write file inside. This mean if you use a container outside GNS3 the data will not be available. But also this mean all the data of the GNS3 project is in the same location.


Add in your Dockerfile
```dockerfile
VOLUME /etc/haproxy/
CMD haproxy -f /etc/haproxy/haproxy.cfg
```

**Comment by AJNOURI** [comment]
Got it. Thanks Julien.
