### ISSUE TITLE
Link between topologies

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#517]
An idea we have see multiple time. A way to communicate between two topologies.

This could be a property of the cloud node two way to do that from user point of view:
- in the cloud you select the cloud node of the other topology
- in the cloud you select a named network (could be internally a VDE network, or a share instance of a switch)

**Comment by noplay** [comment]
https://github.com/GNS3/gns3-gui/issues/22

**Comment by noplay** [comment]
This create a major issue with some emulator: duplicate mac address (IOU, Dynamips, VPCS)

**Comment by noplay** [comment]
After reflexion. We can't do that builtin in GNS3. The problem is GNS3 project are designed to be isolated from each others to avoid mac address collision. And it's impossible to use different mac address in different projects for the following reason:

* after you put a node in a topology we can't change the mac address without breaking your handmade config. If you connect a topology you just duplicate BOOM mac address collision
* mac address range is very limited for IOU, VPCS (255), Dynamips and some Qemu appliance

**Comment by Ztaguassi** [comment]
I now that's an old topic but I have success to connecting projects using a virtual interface on Linux and connecting it to a Cloud.
It worked very well and as expected for me using VLANs.
I have a project that a built my own internet topology and create some "ISPs" on it. So I have connect the last router using a trunk interface to a Cloud with a virtual interface from Linux and create another project that have a Cloud with the same virtual interface and connected to a router with a trunk interface and the communication worked.
I think that if the Software GNS3 create the interfaces only to avoid someone to do shit on Linux it will help very much.

**Comment by b-ehlers** [comment]
@Ztaguassi As you done you can setup some virtual linux interfaces, an even easier method is to use an UDP tunnel between two topologies. That should work also on macOS and Windows.

Here two simple projects:
![project1](https://user-images.githubusercontent.com/49040325/91282109-2b3a5380-e789-11ea-9b1c-4b07180050fd.png) ![project2](https://user-images.githubusercontent.com/49040325/91282116-2ecdda80-e789-11ea-9fd9-37066ef1818c.png)

In the cloud interface create an UDP tunnel using two unused ports. Setup the first UDP tunnel between portA and portB, the second between portB and portA. Here an example using port 60000 and 60001, the second cloud should be configure with interchanged ports:

![cloud_config](https://user-images.githubusercontent.com/49040325/91282123-32616180-e789-11ea-8eaf-e1466f080d99.png)

**BUT** as @noplay stated, you might expirience mac address collision. GNS3 ensures, that you have unique mac addresses within a topology, but nodes may use the same mac addreses in different topologies. Connecting these topologies won't work because of duplicate mac addresses. That can't be solved within GNS3.

If you are very careful and keep an eye on the mac addresses, you can setup a working interconnection between topologies. But there is no general solution, that just works.
