### ISSUE TITLE
Capture is not supported for VPCS and Qemu

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#548]
If we connect two vpcs or two Qemu together actually we can not capture traffic.

**Comment by grossmj** [comment]
There are only 2 ways to support them. Whether have the communication handled by uBridge or Openvswitch.

This would be easy on Linux, just have TAP interfaces bridged to uBridge or Openvswitch. However things are not that simple on Windows/OSX because of the lack of native TAP support. One solution would be to create 2 UDP tunnels (one from Qemu/VPCS to uBridge and another from uBridge to the destination node) but this would be ugly and I find adds overhead.
