### ISSUE TITLE
Bind UDP tunnel to a host

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#664]
Most tunnel are actually bind to a 0.0.0.0 for security we could improve that by binding them to an ip.

This require:
- [ ] Send in the NIO creation the host to bind
- [ ] Patch uBridge to support it https://github.com/GNS3/ubridge/issues/17
- [x] Patch Qemu code to use it (Replace #649)
- [ ] Patch IOU to use it
- [x] Patch docker to use it 
- [x] Patch VPCS to use it 
- [x] Patch VMware to use it
- [x] Patch VirtualBox to use it
- [x] Patch Dynamips to use it

Perhaps for some emulator it's not supported

**Comment by grossmj** [comment]
Dynamips is done but there is a limitation: https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/dynamips/hypervisor.py#L212

**Comment by grossmj** [comment]
It is complicated to patch everything for something that is not really needed, it will just add more complexity. Yes it is more secure but the only thing that should be secure are the connections to the hypervisors/GNS3 servers. The data paths we don't really care since GNS3 is only supposed to be a learning/PoC tool

**Comment by noplay** [comment]
The worst thing that could happen is someone send you blind packet in the hope of a an exploit. But you can never get answer from the OS. If you want to take control of the user computer you need to found a remote exploit in the OS and in the hardware emulator.

**Comment by grossmj** [comment]
Dynamips and VirtualBox do not support binding to a source host.

**Comment by grossmj** [comment]
We mostly need to patch uBridge.

**Comment by grossmj** [comment]
In fact we don't need to patch anything because uBridge creates UDP tunnels on demand. Here is an example with 2 Qemu VMs connected back-to-back:

```
$ sudo lsof -i 4UDP -n
qemu-syst 11035 grossmj   13u  IPv4 149781      0t0  UDP 127.0.0.1:10004 
ubridge   11037 grossmj    5u  IPv4 153373      0t0  UDP 127.0.0.1:10005->127.0.0.1:10004 
ubridge   11037 grossmj    6u  IPv4 153374      0t0  UDP 172.16.45.1:10002->172.16.45.1:10003 
qemu-syst 11233 grossmj   13u  IPv4 155308      0t0  UDP 127.0.0.1:10036 
ubridge   11236 grossmj    5u  IPv4 155311      0t0  UDP 127.0.0.1:10037->127.0.0.1:10036 
ubridge   11236 grossmj    6u  IPv4 155312      0t0  UDP 172.16.45.1:10003->172.16.45.1:10002
```

We can see the local UDP tunnels going from Qemu to uBridge, their source address is 127.0.0.1 (patched in https://github.com/GNS3/gns3-server/commit/f338158654e388bea0164b9db9cf75252ee768e0) so you can only receive something from a local address and the UDP tunnel between the 2 uBridge instances is established and will only accept data from the remote addresses/ports.
