### ISSUE TITLE
 when run pip setup install (aiohttp 1.0.1) Segmentation fault

### ISSUE THREAD

**Issue by jcmartins** [GNS3/gns3-server#684]
Searching for aiohttp>=0.21.5
Reading https://pypi.python.org/simple/aiohttp/
Downloading https://pypi.python.org/packages/f6/17/3111f78d71208424e2f082e682a25eaf75fd9d737123a37b4799392d783b/aiohttp-1.0.1.tar.gz#md5=a66cca5431c0818b1984a054f25f3bc6
Best match: aiohttp 1.0.1
Processing aiohttp-1.0.1.tar.gz
Writing /tmp/easy_install-sik0l81i/aiohttp-1.0.1/setup.cfg
Running aiohttp-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-sik0l81i/aiohttp-1.0.1/egg-dist-tmp-vflh6_31
**Segmentation fault**

**Comment by noplay** [comment]
It's not GNS3 code the problem because it's before GNS3 installation. 

Two possibility:
* It's an issue with pip on your distribution.
* it's a bug in aiohttp but no one reported it for the moment:

I suggest that you try to install aiohttp directly via:
```
pip3 install aiohttp
```

And if it's segfault report the bug here:
https://github.com/KeepSafe/aiohttp

With information about your distributions.
