### ISSUE TITLE
qemu >= 2.4.0 '-machine smm=off' is invalid option

### ISSUE THREAD

**Issue by xsgb** [GNS3/gns3-server#689]
Hi, qemu (2.6) hangs when parsing
`-machine smm=off`

`Execution log:
qemu-system-x86_64: -machine smm=off: invalid option`

I got it start by removing the check [here](https://github.com/GNS3/gns3-server/commit/2bbdbeaa8278dbb1be6974c1d5c864055812ffc1#diff-f1a9dab468340bf5e197601fd141ac77R1430).

PS: using linux 4.7 with i5 CPU on my host, the smm bug mentioned does not show for the moment.

**Comment by noplay** [comment]
Hi,

Thanks for the report.

What is your distribution?  I just test with a qemu 2.7 fresh compiled and the option exists.

**Comment by ehlers** [comment]
Same issue here, Debian stretch/testing, QEMU emulator version 2.6.0 (Debian 1:2.6+dfsg-3.1)

**Comment by noplay** [comment]
Does it fail if you start from a console?
```
qemu-system-x86_64 -curses -machine smm=off

**Comment by ehlers** [comment]
No, that doesn't fail. But I now see the problem.

The qemu command line is something like that:
`/usr/bin/qemu-system-i386 -name MicroCore-1 -m 64M -smp cpus=1 -enable-kvm '-machine smm=off' -boot order=c -drive file=/opt/gns3/projects/135ec864-e33f-4fe7-abe0-7871209a5389/project-files/qemu/5c81b314-341f-4e09-90aa-33eb20d8fe09/hda_disk.qcow2,if=ide,index=0,media=disk -serial telnet:0.0.0.0:5000,server,nowait -monitor tcp:127.0.0.1:58305,server,nowait -net none -device e1000,mac=00:53:89:fe:09:00 -nographic -nographic`

The problem is, that `'-machine smm=off'` is a single parameter. By splitting it in two it works for me.

Here my `git diff`:
```
diff --git a/gns3server/modules/qemu/qemu_vm.py b/gns3server/modules/qemu/qemu_vm.py
index 2fd91e3..01188ab 100644
--- a/gns3server/modules/qemu/qemu_vm.py
+++ b/gns3server/modules/qemu/qemu_vm.py
@@ -1428,7 +1428,7 @@ class QemuVM(BaseVM):
             # Issue on some combo Intel CPU + KVM + Qemu 2.4.0
             # https://github.com/GNS3/gns3-server/issues/685
             if version and parse_version(version) >= parse_version("2.4.0"):
-                command.extend(["-machine smm=off"])
+                command.extend(["-machine", "smm=off"])
         command.extend(["-boot", "order={}".format(self._boot_priority)])
         cdrom_option = self._cdrom_option()
         command.extend(cdrom_option)
```

**Comment by noplay** [comment]
Yeah it seem something has changed in the way qemu parse and the split is
now mandatory

**Comment by noplay** [comment]
It's more logic now.

**Comment by xsgb** [comment]
Sorry for not having spent so much time here… Anyway, thanks you a lot sirs for the awesomely quick solving!

**Comment by noplay** [comment]
Thanks a lot for the report
