### ISSUE TITLE
container snapshots: container not restored

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#731]
Does snapshots backup container's state?

As shown here, looks like it doesn't:
[Test container snapshot](https://youtu.be/cYfVnLVSx8Q)

Knowing that, Docker provides "commit" function that builds an image from a modified container, Is there a way to implement this in GNS3?:
When you snapshot a container, an image is built from the modified container, that will replaces the base image pulled initially.
This way, a re-opened project will generate the container from the committed image (with changes), not the base image.

**Comment by noplay** [comment]
Only the volumes of Docker are saved. Not only when you snapshot but also when you close the project.

We can't use commit because:
* it's not designed for that (if we do that will quickly have images will 100 or 200 overlay disk). 
* commit is a docker operation specific to user computer this mean the topology will not be portable
