### ISSUE TITLE
VPCS and loobpack adapters not working together

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#771]
If you connect VPCS to a loopback adapter, vpcs receive back the packet send by VPCS. This VPCS can't work because when you set an ip VPCS think another device use the same ip on the network.

**Comment by noplay** [comment]
Windows only

**Comment by grossmj** [comment]
I remember now that I had the same issue with VMware and had to implement an option in the preferences, just for Windows (VMware -> Network -> "Block network traffic originating from host OS", enabled by default).

https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/vmware/vmware_vm.py#L330

This works by blocking the source MAC address of the adapter with a PCAP filter.

**Comment by grossmj** [comment]
Maybe we should have that more generic in the code that handles uBridge in GNS3.

**Comment by grossmj** [comment]
I gave some more thoughts to this issue. Isn't the goal of the loopback adapters to communicate with the host OS? So I guess we gonna have an issue if we block anything originating from these adaptors. Maybe that's one reason to look at the 'TAP' driver provided with open VPN... Definitely some more research to do.

**Comment by grossmj** [comment]
My last comment was more intended for https://github.com/GNS3/gns3-gui/issues/1625

**Comment by grossmj** [comment]
My last commit need to be tested. As I said I have concerns about blocking traffic when using a 'Cloud' with an Ethernet adapter.

**Comment by noplay** [comment]
The fix is not working I have the same issue

**Comment by grossmj** [comment]
Have you tested this on Windows 10?

**Comment by noplay** [comment]
Yes it's a Win10

**Comment by grossmj** [comment]
Confirmed, we still have the issue with looped back packets in the last build.

**Comment by grossmj** [comment]
The problem is not the adapter type (loopback) because I have the same issue with VMnet adapters.

**Comment by noplay** [comment]
I just test and the problem is still here :(

**Comment by grossmj** [comment]
Yep, I had little hope with my last commit :( Another thing would be to confirm we have this issue only with VPCS. Saying this because we don't have that problem with VMware but maybe I missed something.

**Comment by grossmj** [comment]
> I gave some more thoughts to this issue. Isn't the goal of the loopback adapters to communicate with the host OS? So I guess we gonna have an issue if we block anything originating from these adaptors. Maybe that's one reason to look at the 'TAP' driver provided with open VPN... Definitely some more research to do.

Well, turns out that I was right. I couldn't ping an Ethernet adapter from a Cisco IOS nor could see any looped back traffic. I am starting to wonder if VPCS does something exotic that creates that problem.

**Comment by noplay** [comment]
We can also cut off the check in VPCS, perhaps other OS just don't complaint if they receive back the broadcast send by them.

**Comment by grossmj** [comment]
Indeed VPCS should ignore frames with its own MAC address as source however
I would like to validate if something is wrong outside VPCS to be sure,
keep the issue open for now. This should not prevent us to release a new
alpha.

On Thu, Nov 24, 2016, 06:52 Julien Duponchelle <notifications@github.com>
wrote:

We can also cut off the check in VPCS, perhaps other OS just don't
complaint if they receive back the broadcast send by them.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/GNS3/gns3-server/issues/771#issuecomment-262621301>,
or mute
the thread

**Comment by grossmj** [comment]
I patched VPCS https://github.com/GNS3/vpcs/commit/aa9d88fbce95476ecb0a317f2cb70c5d1ac16a5e

This need to be tested on Windows

**Comment by noplay** [comment]
When I recompile VPCS with a recent cygwin it's display Send packet error at startup (not an issue with your patch but with cygwin and VPCS code ...).

**Comment by grossmj** [comment]
I cannot test because with the vpcs.exe built on Yosemite I get "unable to create NIO UDP for bridge 'VPCS-53ac41ad-79cf-4ede-8692-56fcd4b5fa30': create_nio_udp: unable to connect to 127.0.0.1:10002" messages when I start a VPCS node. Weird since I don't have that issue with the original executable, maybe it's because I haven't replaced the cygwin DLL but I doubt so.

**Comment by noplay** [comment]
cygwin1.dll is now include in the nightly build https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-12-19/

**Comment by grossmj** [comment]
Confirmed, the DLL has nothing to do with the issue :(

I don't understand what is wrong...

**Comment by grossmj** [comment]
Fixed the test for duplicated IP address

https://github.com/GNS3/vpcs/commit/f110e15306dbf4d77c55675f4834cd762670792c

However, I believe there is something wrong with VPCS compilation on our build server because if I compile locally with Cygwin (gcc-core and make installed), I don't have any problem.

Using the vpcs download from https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-01-12/ leads to https://github.com/GNS3/gns3-server/issues/771#issuecomment-267800691

@noplay can you check why? please :)

**Comment by noplay** [comment]
How do you compile?

I compile with:
bash.exe mk.sh i386

**Comment by grossmj** [comment]
Hi just execute ./mk.sh in Cygwin 64 bit. That may explain why I don't have issues....

**Comment by grossmj** [comment]
I confirm, my vpcs is 64-bit ;)

**Comment by noplay** [comment]
Could you test
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-01-13/vpcs.exe/download

**Comment by grossmj** [comment]
Doesn't work: 'unable to create NIO UDP for bridge 'VPCS-3ab2a4d5-f06c-4ecb-b2d7-2fd09ecf903c': create_nio_udp: unable to connect to 127.0.0.1:10002' :(

**Comment by noplay** [comment]
Shipped your vpcs with beta 3
