### ISSUE TITLE
2.0.0b1 to 2.0.0b2 Schema Changes

### ISSUE THREAD

**Issue by supertylerc** [GNS3/gns3-server#848]
This probably doesn't need to be filed as a bug since it won't be an issue by the time final is released, but it's probably worth existing just as a note for any users upgrading from `2.0.0b1` to `2.0.0b2`: if you have a built-in Ethernet switch, `2.0.0b1` will give it a `console` and `console_type` of `null`.  In `2.0.0b2`, schema validation is performed that causes this to raise a `400`.  Furthermore, it seems the `console` and `console_type` keys aren't valid for `2.0.0b2` the built-in ethernet switch anymore.

Additionally, it looks like for at least Qemu VMs the location of `console` and `console_type` has changed to be nested under `properties`.

**Comment by noplay** [comment]
That strange because I don't have the same behavior.

In last source code:
* Ethernet switch provide console and console_type as null at the top level of the node
* Qemu provide console and console_type with values at the top level of the node

You have no console for ethernet and nested console qemu in new projects?
