### ISSUE TITLE
There is arch-dependent binary on the repository

### ISSUE THREAD

**Issue by leitao** [GNS3/gns3-server#970]
Currently, there is a x86 specific binary on the package, which turns it not portable. 

$  file gns3-server/gns3server/modules/docker/resources/bin/busybox 
gns3-server/gns3server/modules/docker/resources/bin/busybox: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped

**Comment by noplay** [comment]
Hi,

You can rebuild the binary using this busybox repository:
https://github.com/GNS3/busybox

Especially the configuration file from here:
https://github.com/GNS3/busybox/blob/gns3_build/gns3_build/busyboxconfig

If you rebuild busybox with this settings the binary will be fine.


This binary is use only when we we start a docker container and the bin is run inside the container not on your system. I'm not sure that docker will work fine on non x86 machine.  And I don't know the behavior if you open a topology made with x86 docker on a arm or powerpc 

Actually we provide a precompiled version the binary as a part of the repository to simplify the life, but this could be improved.

I think we could provide multiple precompiled bin and select one based on system arch. Or this could be an external package.

**Comment by the-maldridge** [comment]
I support it being an external package.  I just ran into this building a gns3 package for Void Linux, and it took me a little bit to figure out why the C symbol stripper was interested in, what I thought, was a pure Python egg.

**Comment by Vaelatern** [comment]
Perhaps it could be a build option "Use system busybox" or something like that?

**Comment by noplay** [comment]
Using the system busybox will not work. Because when  you compile busybox you need to provide the path of where the binary will be located. In our busybox we set the path to /gns3/bin/busybox this allow us to avoid conflicting with the content of the docker container (we inject this busybox in docker containers).

**Comment by Vaelatern** [comment]
Yet for other builds, not for docker containers, the system busybox should work?

**Comment by noplay** [comment]
Busybox is use only in the docker container.

**Comment by CameronNemo** [comment]
@vaelatern: afaiu gns3 uses docker as a back-end for pseudo virtualization. It is not in a container in the back-end. We could always just rm the binary in post install and declare the back-end unsupported, no?

**Comment by noplay** [comment]
@CameronNemo we need to make sure the busybox binary is compiled with all require command. It's not the case for all containers. Also the binary need to be static, otherwise you will need also to inject the libs. But it's a possibility if we could inject the system busybox instead and avoid shipping a bin.

Ideally we should provide an easy for packager to rebuild the busybox. But not sure how it's fit with python packaging.

**Comment by CameronNemo** [comment]
Please provide a list of required busybox commands. Why are you unable to put the busybox binary in the container image?

**Comment by noplay** [comment]
We can't put the busybox binary in the container because we don't control the container image.  You can grab any container from the Docker Hub and run it with GNS3. Image are provided by network manufacturer for example.  We know that is far from ideal, but the way we use Docker is not really standard we emulate lightweight computer with multiple network interfaces with it. 

The command include in the binary are available here:
https://github.com/GNS3/busybox/blob/gns3_build/gns3_build/busyboxconfig

**Comment by grossmj** [comment]
Will be resolved in https://github.com/GNS3/gns3-server/issues/1890
